### DISCUSSION TITLE
Need help to backup types

### DISCUSSION THREAD

**Discussion by marmik18** [datanymizer/datanymizer#124] [Q&A] [answered]
I need to back up `types` with the schema and the data. When I verify the dump, I see that the data and schema has been successfully dumped, but the types are not. Can someone please show how can i dump the `types` as well.

**Comment by evgeniy-r** [comment]
I will take a look.

**Reply by marmik18** [reply]
I tried filters for this, but that also does not work, for eg:
### config
```yaml
...
filter:
  schema:
    only:
      ...
      - default$default.SomeType
```

**Comment by evgeniy-r** [comment, marked as answer]
It seems like the only option is to use a config like this:
```yaml
filter:
  schema:
    except:
      ........
```

Or this:
```yaml
filter:
  data:
    only:
      ........
```
