### ISSUE TITLE
Issue with reading from key value store

### ISSUE THREAD

**Issue by marmik18** [datanymizer/datanymizer#120]
Hi @evgeniy-r , I am facing some issues while using the key-value store. please correct me if I am using it wrong. 
`User` is connected to `Profile` with a foreign key in the `User` table. So I am using `profile_id` while storing the data to the store and then while retrieving I am just using the `id` from the `Profile` table.

### Config
```yaml
tables:
  - name: User
    rules:
      phone:
        template:
          format: "{{ _1 }}{{ store_write(key='user_phonenumbers.' ~ prev.profile_id, value=_1) }}"
          rules:
            - phone:
                format: "+############"
                uniq: true
  - name: Profile
    rules:
      phone:
        # reading phone numbers from `user_phonenumbers` stored in `User`
        template:
          format: "{{ store_read(key='user_phonenumbers.' ~ prev.id) }}"
```

### Output
```bash
...
Prepare to dump table: default$default.Profile
Error: Failed transform Failed to render 'TemplateTransformerTemplate'
ERROR: Job failed: exit code 1
FATAL: exit code 1         
```

Just to confirm that whether the template is giving an error on reading, I tried removing the `template` under `Profile` and replaced it with `phone` to randomize it and it works that way. So I am quite sure that there is something wrong - either how I am implementing it or with the anonymizer.
