### ISSUE TITLE
Execution order for tables

### ISSUE THREAD

**Issue by marmik18** [datanymizer/datanymizer#125]
Is there a way to define an execution sequence for the tables? As the values for the store are not stored before the read operation starts. Swapping the sequence in the config works, but it is inconsistent and fails after some runs.
```yaml
tables:
  - name: User
  ...
    template:
      format: "{{ store_read(...) }}"
  ...
  - name: Profile
  ...
    template:
      format: "{{ store_write(...) }}"
  ...
```
