### ISSUE TITLE
Feature Request: wildcards in filters

### ISSUE THREAD

**Issue by marmik18** [datanymizer/datanymizer#139]
Currently, I have 100s of tables in my database, all under different schemas. 
I want to anonymize around 5 - 10 of my tables. I am able to achieve this using the following config
```yaml
.....
filter:
  data:
    only:
      - "default$default.Profile"
      ...
```
Potentially, this creates another issue as it copies over the other schema, which I don't want to copy.

When I try to use the following config:
```yaml
.....
filter:
  schema:
    only:
      - "default$default.Profile"
      ...
```
Only the tables selected get copy but not their dependencies, for e.g. ENUMs used in those tables.

So I would like to request for a feature in which filter accepts wildcard `*` for anything under a schema.
something like:
```yaml
filter:
  schema:
    only:
      - "default$default.*"
    except:
      - "public.*"
```

Thank you in advance.
