### ISSUE TITLE
Error when run pg_datanymizer periodically

### ISSUE THREAD

**Issue by cool-tiger** [datanymizer/datanymizer#163]
Hi, thank you for your product, it's awesome.
I have a problem when start pg_datanymizer
```
I have no name!@datanymizer-db4bdb45f-rqnx9:/tmp$ /pg_datanymizer -f /tmp/dump.sql -c ./config.yaml postgres://test:test@postgresql-test/test
Prepare data scheme...
Fetch tables metadata...
[1 / 2] Prepare to dump table: xavier_dev.candidates
[Dumping: xavier_dev.candidates] --- SKIP ---
[2 / 2] Prepare to dump table: xavier_dev.tmp_candidates
Error: Failed transform Failed to render 'TemplateTransformerTemplate'
```
But sometimes it finishes successfully without any changes
```
I have no name!@datanymizer-db4bdb45f-rqnx9:/tmp$ /pg_datanymizer -f /tmp/dump.sql -c ./config.yaml postgres://test:test@postgresql-test/test
Prepare data scheme...
Fetch tables metadata...
[1 / 2] Prepare to dump table: xavier_dev.tmp_candidates
Error: Failed transform Failed to render 'TemplateTransformerTemplate'
I have no name!@datanymizer-db4bdb45f-rqnx9:/tmp$ /pg_datanymizer -f /tmp/dump.sql -c ./config.yaml postgres://test:test@postgresql-test/test
Prepare data scheme...
Fetch tables metadata...
[1 / 2] Prepare to dump table: xavier_dev.tmp_candidates
[Dumping: xavier_dev.tmp_candidates] [|##################################################|] 0 of 0 rows [100%] (0s)
[Dumping: xavier_dev.tmp_candidates] Finished in 0 seconds
[2 / 2] Prepare to dump table: xavier_dev.candidates
[Dumping: xavier_dev.candidates] --- SKIP ---
Finishing with indexes...
```
This is my config
```
default:
  locale: RU
filter:
  schema:
    only:
      - xavier_dev.tmp_candidates
tables:
  - name: tmp_candidates
    query:
      limit: 3
    rules:
      first_name:
        first_name: {}
      last_name:
        last_name: {}
      other_name:
        middle_name: {}
      search_full_name:
        template:
          format: "{{final.last_name}} {{final.first_name}} {{final.other_name}}"
```
I think error can be in the search_full_name rule, but can't understand where. Without this rule all work fine.
Can you help me?
