### ISSUE TITLE
No start value for create / alter sequence (PG 13)

### ISSUE THREAD

**Issue by fryck** [datanymizer/datanymizer#187]
Hi, it seems that there is missing information about sequence start position.

For example, in my production database I have in `pg_catalog.pg_sequences` on my table `media`

<img width="1200" alt="Screenshot 2022-10-04 at 13 40 11" src="https://user-images.githubusercontent.com/1364225/193810866-964b5055-dfb2-403a-a529-c59208c4fab9.png">

**Command:**

`pg_datanymizer -c ./config.yml -f ./dumpl.sql -- postgres://xxx:xxx@127.0.0.1:5432/db-name`

**Config.yml:**

```
tables:
  - name: member
    rules:
      username:
        username:
          uniq:
            required: true
            try_count: 5
      email:
         email:
           kind: Safe
           prefix: 20
           affix_separator: "__"
           uniq:
             required: true
             try_count: 5
      first_name:
        first_name: {}
      last_name:
        last_name: {}
      postal_code:
        post_code: {}
      phone:
        phone: {}
filter:
  only:
    - public.media
```

When dump only the `media` table and I inspect the dump file :

```
--
-- Name: hd_capture_id_seq; Type: SEQUENCE; Schema: public; Owner: prodUser
--

CREATE SEQUENCE public.hd_capture_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
--
```

Is it a bug ? or I miss something ? Thanks !
