### ISSUE TITLE
Error: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by marmik18** [datanymizer/datanymizer#190]
I have tried running the following command
```bash
./bin/pg_datanymizer -f backup.sql -c ./test.yml postgresql://postgres:postgres@172.19.0.3:5432/postgres
```
  
where the `test.yml` is   
  
```yaml
tables:
  - name: Profile
    rules:
      firstName:
        first_name: {}
      lastName:
        last_name: {}
```
Also i have tried running this on the following OS / Environments:

- macOS 12.4
- Ubuntu 20.04
- Node:16.15-alpine (docker engine, both on macOS 12.4 and Ubuntu 20.04)
