### ISSUE TITLE
Anonymize array fields

### ISSUE THREAD

**Issue by bvicenzo** [datanymizer/datanymizer#191]
Hi. 
I'd like to know how I would anonymize an [array field](https://www.postgresql.org/docs/current/arrays.html) such as an array of emails.
Is it possible? I didn't find how.

Thanks!

Best regards!

**Comment by grvm** [comment]
Sharing what worked for me here, in case anyone is interested, its pretty simple actually:

```yml
some_array_column:
  template:
    format: "{ {{ _1 }} }"
    rules:
      - email: {}
```

So basically, you enclose a string in `{}` and it would be saved as an array, if the column is an array in postgres
