### ISSUE TITLE
Add template references to other transformed values of the same row

### ISSUE THREAD

**Issue by evgeniy-r** [datanymizer/datanymizer#32]
Possible syntax (look at `tr`):
```yaml
tables:
  - name: users
    rules:
      login:
        username: {}
      preferences:
        template:
          format: '{"some_complex_json": {"field": "{{tr.login}}"}}'
```
Tera allows also `tr["login"]`.

The name `tr` means "transformed row". We can use `tr_row` or `transformed_row` instead (it might be too long).

We can also use just `row`, but what if in the future we decide to use the values ​​of the original row too?
