### ISSUE TITLE
Add the limit when dumping data

### ISSUE THREAD

**Issue by evgeniy-r** [datanymizer/datanymizer#33]
Possible config syntax:

```yaml
tables:
  - users:
    # per table
    limit: 10000
    # ........................
default:
  # global
  limit: 1000
```

We can also think about more flexible customization - specifying an SQL query for the table.

**Comment by evgeniy-r** [comment]
@akirill0v, what do you think?

**Comment by akirill0v** [comment]
Perhaps it would be better to add a custom SQL conditional query? For example:

```
tables:
  - users:
    # per table
    query: age > 18 or age < 50 and state = 'enabled'
    # ........................
default:
  # global
  query: limit 1000
```

How the parts of the query affect each other (global condition and table condition) may be discussed below. My guess is they are concatenated via the `AND` operator.
