### ISSUE TITLE
pg_datanymizer not work in container

### ISSUE THREAD

**Issue by agmayer** [datanymizer/datanymizer#37]
I run demo as it say in demo/README.md.
I build a container with pg_datanymizer in and run via `make dump`
But I get an error:
```
Error: invalid type: unit value, expected struct FirstNameTransformer
```

If I comment in `dvdrental.yml` block for `first_name`, like this:
```yaml
filter:
  only:
    - public.actor
tables:
  - name: actor
    rules:
#      first_name:
#        first_name: ~
      last_name:
        last_name: ~
      last_update:
        datetime:
          from: 1990-01-01T00:00:00+00:00
          to: 2010-12-31T00:00:00+00:00
```
Then i get same error with `last_name`:
```
Error: invalid type: unit value, expected struct LastNameTransformer
```

After add comment for `last_name`, like this:
```yaml
filter:
  only:
    - public.actor
tables:
  - name: actor
    rules:
#      first_name:
#        first_name: ~
#      last_name:
#        last_name: ~
      last_update:
        datetime:
          from: 1990-01-01T00:00:00+00:00
          to: 2010-12-31T00:00:00+00:00
```
All works fine.

When I build container with postgresql and download pg_datanymizer CLI into it all works fine!

My Dockerfile for example - [Link](https://github.com/agmayer/datanymizer/blob/bugfix/pg_datanymizer_docker_image/demo/Dockerfile.pg_datanymizer)

Builded container in DockerHub - agmayer/pg_datanymizer

**Comment by evgeniy-r** [comment]
There was a slight change in the syntax of datanymizer config, you should use `{}` instead of `~`:

```yaml
filter:
  only:
    - public.actor
tables:
  - name: actor
    rules:
      first_name:
        first_name: {}
      last_name:
        last_name: {}
      last_update:
        datetime:
          from: 1990-01-01T00:00:00+00:00
          to: 2010-12-31T00:00:00+00:00
```

Thanks for the report.

We will update the docs.
