### ISSUE TITLE
Failed after schema change. 

### ISSUE THREAD

**Issue by Erzed** [datanymizer/datanymizer#68]
DB:
```sql
create table "user"
(
	id serial,
	first_name text,
	last_name text,
	email_field text
);

insert into "user" (first_name, last_name, email_field) VALUES ('A', 'B', 'c@example.com');
alter table "user" drop column last_name;
```

Config:
```yaml
tables:
  - name: "user"
    rules:
      email_field:
        email:
          kind: Safe
```

Error:
```
thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 3', datanymizer_engine/src/engine.rs:40:25
```
