### ISSUE TITLE
Error: no matching tables were found

### ISSUE THREAD

**Issue by marmik18** [datanymizer/datanymizer#93]
@evgeniy-r I am facing an issue while using the cli with my db. I am not sure that whether I am using the config correctly, can you help me rectify the issue. 

thank you in advance.

### Background
I have a database with multiple schemas and I want to copy over the schema `default$default` and the tables under that schema. Of course, I also anonymize certain fields in the tables.

### config.yml
```
tables:
  - name: default$default.Profile
    rules:
      firstName:
        first_name: {}
        ...
        ...
filter:
  schema:
    only:
      - default$default
```

### Output
```
$ ./bin/pg_datanymizer -f backup.sql -c anonymizer/config.yml --accept_invalid_certs $POSTGRES_CONNECTION_STRING
Prepare data scheme...
pg_dump error. Command:
pg_dump --section pre-data -t default$default <POSTGRES_CONNECTION_STRING>
Output:
pg_dump: error: no matching tables were found
```

**Comment by evgeniy-r** [comment]
I will take a look.

**Comment by evgeniy-r** [comment]
In the `schema`section you should place a list of tables, for which you want to dump their schema (structure), not a schema name.
```yaml
filter:
  schema:
    only:
      - default$default.Profile
      - ...........
```
We will think about using wildcards (`*`).

Also, in the `tables` section please use names without a schema (it is an old issue, we should fix it, but the most of people anonymize data in just one schema, so it hasn't been fixed yet):
```yaml
tables:
  - name: Profile
  - rules:
  .............
```

**Comment by marmik18** [comment]
understood. 
Tried the following and it is giving me the same error.

### config.yml
```
tables:
  # Table name in database
  - name: Profile
    rules:
      firstName:
        first_name: {}
        ...
        ...
filter:
  schema:
    only:
      - default$default.Profile
```
### output
```
$ ./bin/pg_datanymizer -f backup.sql -c anonymizer/config.yml --accept_invalid_certs $POSTGRES_CONNECTION_STRING
Prepare data scheme...
pg_dump error. Command:
pg_dump --section pre-data -t default$default.Profile  <POSTGRES_CONNECTION_STRING>
Output:
pg_dump: error: no matching tables were found
```
